# Generated by Django 3.2.5 on 2021-07-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_envio_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('comuna', models.CharField(max_length=100)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.envio')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('comuna', models.CharField(max_length=100)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcel.envio')),
            ],
        ),
    ]
